# Generated by Django 4.2.6 on 2023-11-02 00:11

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import projects.validators


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'address_line',
                    models.CharField(
                        max_length=100, verbose_name='Адрес в одну строчку'
                    ),
                ),
                (
                    'street',
                    models.CharField(max_length=75, verbose_name='Улица'),
                ),
                ('house', models.CharField(max_length=5, verbose_name='Дом')),
                (
                    'block',
                    models.CharField(max_length=5, verbose_name='Корпус'),
                ),
                (
                    'building',
                    models.CharField(max_length=5, verbose_name='Строение'),
                ),
            ],
            options={
                'verbose_name': 'Адрес проекта',
                'verbose_name_plural': 'Адреса проектов',
            },
        ),
        migrations.CreateModel(
            name='ProjectIncomes',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'status_incomes',
                    models.CharField(
                        choices=[
                            ('application_submitted', 'Заявка подана'),
                            ('rejected', 'Отклонена'),
                            ('accepted', 'Принята'),
                        ],
                        default='application_submitted',
                        max_length=100,
                        verbose_name='Статус заявки волонтера',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name='Статус заявки волонтера',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Заявки волонтеров',
                'verbose_name_plural': 'Заявки волонтеров',
            },
        ),
        migrations.CreateModel(
            name='ProjectSkills',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerFavorite',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name='projectparticipants',
            options={
                'default_related_name': 'projects_volunteers',
                'verbose_name': 'Участник проекта',
                'verbose_name_plural': 'Участники проекта',
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='application_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_datatime',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_datatime',
        ),
        migrations.AddField(
            model_name='organization',
            name='photo',
            field=models.ImageField(
                blank=True, upload_to='', verbose_name='Фото'
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(
                related_name='projects',
                to='projects.category',
                verbose_name='Категории',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date_application',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='Дата и время, окончания подачи заявок',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='end_datetime',
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 2, 0, 11, 1, 11493),
                verbose_name='Дата и время, окончания мероприятия',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='organizer_provides',
            field=models.TextField(
                blank=True, verbose_name='Организатор предоставляет'
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='project_events',
            field=models.TextField(
                blank=True, verbose_name='Мероприятия на проекте'
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='project_tasks',
            field=models.TextField(
                default='asdasdasdasdasdasd', verbose_name='Задачи проекта'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='start_date_application',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='Дата и время, начало подачи заявок',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='start_datetime',
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 2, 0, 11, 39, 155435),
                verbose_name='Дата и время, начало мероприятия',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='about',
            field=models.TextField(blank=True, verbose_name='Об организации'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='organization',
                to='content.city',
                verbose_name='Город',
            ),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contact_person',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='organization',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Пользователь',
            ),
        ),
        migrations.AlterField(
            model_name='organization',
            name='title',
            field=models.CharField(
                max_length=100,
                validators=[projects.validators.validate_title],
                verbose_name='Название',
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status_approve',
            field=models.CharField(
                choices=[
                    ('approved', 'Одобрено'),
                    ('editing', 'Черновик'),
                    ('pending', 'На рассмотрении'),
                    ('rejected', 'Отклонено'),
                    ('canceled_by_organizer', 'Отменено организатором'),
                ],
                default='pending',
                max_length=50,
                verbose_name='Статус проверки',
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='status_project',
            field=models.CharField(
                choices=[
                    ('open', 'Открыт'),
                    ('ready_for_feedback', 'Готов к откликам'),
                    (
                        'reception_of_responses_closed',
                        'Прием откликов окончен',
                    ),
                    ('project_completed', 'Проект завершен'),
                ],
                default='editing',
                max_length=100,
                verbose_name='Статус проекта',
            ),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='date_of_birth',
            field=models.DateField(
                help_text='Введите дату в формате "ГГГГ.ММ.ДД", пример: "2000 01 01".',
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(1900, 1, 1)
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date(2023, 11, 2)
                    ),
                ],
                verbose_name='Дата рождения',
            ),
        ),
        migrations.AddConstraint(
            model_name='projectparticipants',
            constraint=models.UniqueConstraint(
                fields=('project', 'volunteer'),
                name='projectsprojectparticipants_unique_project_volunteer',
            ),
        ),
        migrations.AddField(
            model_name='volunteerfavorite',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='projects.project',
            ),
        ),
        migrations.AddField(
            model_name='volunteerfavorite',
            name='volunteer',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='projects.volunteer',
            ),
        ),
        migrations.AddField(
            model_name='projectskills',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='projects.project',
            ),
        ),
        migrations.AddField(
            model_name='projectskills',
            name='skill',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='content.skills',
            ),
        ),
        migrations.AddField(
            model_name='projectincomes',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='project_incomes',
                to='projects.project',
                verbose_name='Проект',
            ),
        ),
        migrations.AddField(
            model_name='projectincomes',
            name='volunteer',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='project_incomes',
                to='projects.volunteer',
                verbose_name='Волонтер',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='event_address',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='projects.address',
                verbose_name='Адрес проведения проекта',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(
                blank=True,
                related_name='projects',
                through='projects.ProjectSkills',
                to='content.skills',
                verbose_name='Навыки',
            ),
        ),
        migrations.AddConstraint(
            model_name='volunteerfavorite',
            constraint=models.UniqueConstraint(
                fields=('volunteer', 'project'),
                name='unique_volunteer_favorites',
            ),
        ),
        migrations.AddConstraint(
            model_name='projectincomes',
            constraint=models.UniqueConstraint(
                fields=('project', 'volunteer', 'status_incomes'),
                name='projectsprojectincomes_unique_project_volunteer',
            ),
        ),
    ]
