# Generated by Django 4.2.6 on 2023-11-21 20:28

import datetime
import django.core.validators
from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(on_delete=models.SET(projects.models.get_deleted_organization), related_name='projects', to='projects.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='projectincomes',
            name='volunteer',
            field=models.ForeignKey(on_delete=models.SET(projects.models.get_deleted_volunteer), related_name='project_incomes', to='projects.volunteer', verbose_name='Волонтер'),
        ),
        migrations.AlterField(
            model_name='projectparticipants',
            name='volunteer',
            field=models.ForeignKey(on_delete=models.SET(projects.models.get_deleted_volunteer), to='projects.volunteer'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1900, 1, 1)), django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 11, 21))], verbose_name='Дата рождения'),
        ),
    ]
