# Generated by Django 4.2.6 on 2023-11-18 22:24

from django.db import migrations, models
import projects.validators


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_admin_comments_alter_project_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectincomes',
            name='phone',
            field=models.CharField(blank=True, max_length=12, validators=[projects.validators.validate_phone_number], verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='projectincomes',
            name='telegram',
            field=models.CharField(blank=True, max_length=32, validators=[projects.validators.validate_telegram], verbose_name='Телеграм'),
        ),
    ]
