# Generated by Django 4.2.6 on 2023-11-04 16:06

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_volunteer_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectparticipants',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='participant',
                to='projects.project',
            ),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='date_of_birth',
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(1900, 1, 1)
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date(2023, 11, 4)
                    ),
                ],
                verbose_name='Дата рождения',
            ),
        ),
    ]
