# Generated by Django 4.2.6 on 2023-11-30 22:27

import datetime
import django.core.validators
from django.db import migrations, models
import projects.validators


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectincomes',
            name='cover_letter',
            field=models.TextField(blank=True, null=True, validators=[projects.validators.validate_text_cover_letter], verbose_name='Сопроводительное письмо'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1900, 1, 1)), django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 11, 30))], verbose_name='Дата рождения'),
        ),
    ]
