# Generated by Django 4.2.6 on 2023-11-18 23:03

from django.db import migrations, models
import projects.validators


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectincomes_phone_projectincomes_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectincomes',
            name='cover_letter',
            field=models.TextField(blank=True, null=True, validators=[projects.validators.validate_about], verbose_name='Сопроводительное письмо'),
        ),
    ]
