# Generated by Django 4.2.6 on 2023-11-04 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectparticipants_project_and_more'),
        ('projects', '0004_alter_category_name_alter_project_name'),
    ]

    operations = []
