# Generated by Django 4.2.6 on 2023-10-20 19:10

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0006_alter_category_slug_projectincomes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectincomes',
            options={
                'verbose_name': 'Заявки волонтеров',
                'verbose_name_plural': 'Заявки волонтеров',
            },
        ),
        migrations.AddField(
            model_name='projectincomes',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=None,
                verbose_name='Статус заявки волонтера',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectincomes',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='project_incomes',
                to='projects.project',
                unique=True,
                verbose_name='Проект',
            ),
        ),
        migrations.AlterField(
            model_name='projectincomes',
            name='status_incomes',
            field=models.CharField(
                blank=True,
                choices=[
                    ('application_submitted', 'Заявка подана'),
                    ('rejected', 'Отклонена'),
                    ('accepted', 'Принята'),
                ],
                default=None,
                null=True,
                unique=True,
                verbose_name='Статус заявки волонтера',
            ),
        ),
        migrations.AlterField(
            model_name='projectincomes',
            name='volunteer',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='project_incomes',
                to='projects.volunteer',
                unique=True,
                verbose_name='Волонтер',
            ),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='date_of_birth',
            field=models.DateField(
                help_text='Введите дату в формате "ДД.ММ.ГГГГ", пример: "01 01 2000".',
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(1900, 1, 1)
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date(2023, 10, 20)
                    ),
                ],
                verbose_name='Дата рождения',
            ),
        ),
    ]
