# Generated by Django 4.2.6 on 2023-11-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_projectparticipants_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='block',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='address',
            name='building',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Строение'),
        ),
    ]
