# Generated by Django 4.2.6 on 2023-11-04 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_address_block_alter_address_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectparticipants',
            name='volunteer',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='participant',
                to='projects.volunteer',
            ),
        ),
    ]
