# Generated by Django 4.2.6 on 2023-10-21 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_organization_photo_alter_volunteer_date_of_birth'),
        ('projects', '0009_alter_volunteer_date_of_birth'),
    ]

    operations = [
    ]
