# Generated by Django 4.2.6 on 2023-10-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_merge_20231021_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectincomes',
            name='status_incomes',
            field=models.CharField(blank=True, choices=[('application_submitted', 'Заявка подана'), ('rejected', 'Отклонена'), ('accepted', 'Принята')], default=None, max_length=100, null=True, verbose_name='Статус заявки волонтера'),
        ),
        migrations.AddConstraint(
            model_name='projectparticipants',
            constraint=models.UniqueConstraint(fields=('project', 'volunteer'), name='projectsprojectparticipants_unique_project_volunteer_projectparticipants'),
        ),
    ]
