# Generated by Django 4.2.6 on 2023-11-05 01:45

from django.db import migrations, models
import projects.validators


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_volunteer_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(validators=[projects.validators.LengthValidator(max_length=750, min_length=10)], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='event_purpose',
            field=models.TextField(validators=[projects.validators.LengthValidator(max_length=750, min_length=10)], verbose_name='Цель проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='project',
            name='organizer_provides',
            field=models.TextField(blank=True, validators=[projects.validators.LengthValidator(max_length=750, min_length=2)], verbose_name='Организатор предоставляет'),
        ),
        migrations.AlterField(
            model_name='project',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='projects.projectparticipants', verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_events',
            field=models.TextField(validators=[projects.validators.LengthValidator(max_length=750, min_length=2)], verbose_name='Мероприятия на проекте'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_tasks',
            field=models.TextField(validators=[projects.validators.LengthValidator(max_length=750, min_length=2)], verbose_name='Задачи проекта'),
        ),
    ]
