# Generated by Django 4.2.6 on 2023-10-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_projectincomes_status_incomes_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projectparticipants',
            name='projectsprojectparticipants_unique_project_volunteer_projectparticipants',
        ),
        migrations.AddConstraint(
            model_name='projectparticipants',
            constraint=models.UniqueConstraint(fields=('project', 'volunteer'), name='projectsprojectparticipants_unique_project_volunteer'),
        ),
    ]
