# Generated by Django 4.2.6 on 2023-10-23 09:46

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'projects',
            '0012_remove_projectparticipants_projectsprojectparticipants_unique_project_volunteer_projectparticipants_',
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectparticipants',
            options={
                'default_related_name': 'projects_volunteers',
                'verbose_name': 'Участник проекта',
                'verbose_name_plural': 'Участники проекта',
            },
        ),
        migrations.AlterField(
            model_name='organization',
            name='about',
            field=models.TextField(blank=True, verbose_name='Об организации'),
        ),
        migrations.AlterField(
            model_name='projectincomes',
            name='status_incomes',
            field=models.CharField(
                choices=[
                    ('application_submitted', 'Заявка подана'),
                    ('rejected', 'Отклонена'),
                    ('accepted', 'Принята'),
                ],
                default='application_submitted',
                max_length=100,
                verbose_name='Статус заявки волонтера',
            ),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='date_of_birth',
            field=models.DateField(
                help_text='Введите дату в формате "ДД.ММ.ГГГГ", пример: "01 01 2000".',
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(1900, 1, 1)
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date(2023, 10, 23)
                    ),
                ],
                verbose_name='Дата рождения',
            ),
        ),
    ]
