# Generated by Django 4.2.6 on 2023-11-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_project_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='participants',
            field=models.ManyToManyField(related_name='projects', to='projects.projectparticipants', verbose_name='Участники'),
        ),
    ]
