# Generated by Django 4.2.6 on 2023-10-24 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            'projects',
            '0014_project_organizer_provides_project_project_events_and_more',
        ),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerFavorite',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='projects.project',
                    ),
                ),
                (
                    'volunteer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='projects.volunteer',
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='volunteerfavorite',
            constraint=models.UniqueConstraint(
                fields=('volunteer', 'project'),
                name='unique_volunteer_favorites',
            ),
        ),
    ]
