# Generated by Django 4.2.6 on 2023-10-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_volunteerfavorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status_approve',
            field=models.CharField(
                choices=[
                    ('approved', 'Одобрено'),
                    ('editing', 'Черновик'),
                    ('pending', 'На рассмотрении'),
                    ('rejected', 'Отклонено'),
                ],
                default='pending',
                max_length=50,
                verbose_name='Статус проверки',
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='status_project',
            field=models.CharField(
                choices=[
                    ('open', 'Открыт'),
                    ('ready_for_feedback', 'Готов к откликам'),
                    (
                        'reception_of_responses_closed',
                        'Прием откликов окончен',
                    ),
                    ('project_completed', 'Проект завершен'),
                ],
                default='editing',
                max_length=100,
                verbose_name='Статус проекта',
            ),
        ),
    ]
