# Generated by Django 4.2.6 on 2023-11-08 21:41

import datetime
import django.core.validators
from django.db import migrations, models
import projects.validators


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_organization_contact_person_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('start_datetime',), 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AddField(
            model_name='projectincomes',
            name='cover_letter',
            field=models.TextField(blank=True, null=True, validators=[projects.validators.regex_string_validator, projects.validators.LengthValidator(max_length=750, min_length=10)], verbose_name='Сопроводительное письмо'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='date_of_birth',
            field=models.DateField(help_text='Введите дату в формате "ГГГГ-ММ-ДД", пример: "2000-01-01".', validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1900, 1, 1)), django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 11, 8))], verbose_name='Дата рождения'),
        ),
    ]
