# Generated by Django 4.2.6 on 2023-10-25 09:14

from django.db import migrations, models
import projects.validators


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_project_project_tasks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='telegram',
            field=models.CharField(
                blank=True,
                max_length=32,
                validators=[projects.validators.validate_telegram],
            ),
        ),
    ]
