# Generated by Django 4.2.6 on 2023-10-26 08:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_project_project_tasks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='end_datatime',
            new_name='end_datetime',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='start_datatime',
            new_name='start_datetime',
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='date_of_birth',
            field=models.DateField(help_text='Введите дату в формате "ДД.ММ.ГГГГ", пример: "01 01 2000".', validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1900, 1, 1)), django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 10, 26))], verbose_name='Дата рождения'),
        ),
    ]
