# Generated by Django 4.2.6 on 2023-10-27 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_volunteer_telegram'),
        ('projects', '0018_rename_end_datatime_project_end_datetime_and_more'),
    ]

    operations = []
