# Generated by Django 4.2.6 on 2023-10-27 06:28

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_merge_20231027_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'address_line',
                    models.CharField(
                        max_length=100, verbose_name='Адрес в одну строчку'
                    ),
                ),
                (
                    'street',
                    models.CharField(max_length=75, verbose_name='Улица'),
                ),
                ('house', models.CharField(max_length=5, verbose_name='Дом')),
                (
                    'block',
                    models.CharField(max_length=5, verbose_name='Корпус'),
                ),
                (
                    'building',
                    models.CharField(max_length=5, verbose_name='Строение'),
                ),
            ],
            options={
                'verbose_name': 'Адрес проекта',
                'verbose_name_plural': 'Адреса проектов',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='project_tasks',
            field=models.TextField(blank=True, verbose_name='Задачи проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status_approve',
            field=models.CharField(
                choices=[
                    ('approved', 'Одобрено'),
                    ('editing', 'Черновик'),
                    ('pending', 'На рассмотрении'),
                    ('rejected', 'Отклонено'),
                ],
                default='editing',
                max_length=50,
                verbose_name='Статус проверки',
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='status_project',
            field=models.CharField(
                choices=[
                    ('open', 'Открыт'),
                    ('ready_for_feedback', 'Готов к откликам'),
                    (
                        'reception_of_responses_closed',
                        'Прием откликов окончен',
                    ),
                    ('project_completed', 'Проект завершен'),
                ],
                default='open',
                max_length=100,
                verbose_name='Статус проекта',
            ),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='date_of_birth',
            field=models.DateField(
                help_text='Введите дату в формате "ДД.ММ.ГГГГ", пример: "01 01 2000".',
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(1900, 1, 1)
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date(2023, 10, 27)
                    ),
                ],
                verbose_name='Дата рождения',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='event_address',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='projects.address',
                verbose_name='Адрес проведения проекта',
            ),
        ),
    ]
