# Generated by Django 4.2.6 on 2023-10-27 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_address_alter_project_project_tasks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='event_address',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='projects.address',
                verbose_name='Адрес проведения проекта',
            ),
        ),
    ]
