# Generated by Django 4.2.6 on 2023-10-27 15:59

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_alter_project_event_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_tasks',
            field=models.TextField(
                blank=True, null=True, verbose_name='Задачи проекта'
            ),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='date_of_birth',
            field=models.DateField(
                help_text='Введите дату в формате "ГГГГ.ММ.ДД", пример: "2000 01 01".',
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(1900, 1, 1)
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date(2023, 10, 27)
                    ),
                ],
                verbose_name='Дата рождения',
            ),
        ),
    ]
