# Generated by Django 4.2.6 on 2023-10-30 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_volunteer_date_of_birth'),
        ('projects', '0023_alter_category_name_alter_organization_title_and_more'),
        ('projects', '0023_remove_project_category_project_categories_and_more'),
    ]

    operations = [
    ]
