# Generated by Django 4.2.6 on 2023-11-01 10:32

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import projects.validators


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_merge_20231030_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='application_date',
        ),
        migrations.AddField(
            model_name='project',
            name='end_date_application',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время, окончания подачи заявок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='start_date_application',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время, начало подачи заявок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='end_datetime',
            field=models.DateTimeField(verbose_name='Дата и время, окончания мероприятия'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_tasks',
            field=models.TextField(default=1, verbose_name='Задачи проекта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='start_datetime',
            field=models.DateTimeField(verbose_name='Дата и время, начало мероприятия'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status_approve',
            field=models.CharField(choices=[('approved', 'Одобрено'), ('editing', 'Черновик'), ('pending', 'На рассмотрении'), ('rejected', 'Отклонено'), ('canceled_by_organizer', 'Отменено организатором')], default='pending', max_length=50, verbose_name='Статус проверки'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status_project',
            field=models.CharField(choices=[('open', 'Открыт'), ('ready_for_feedback', 'Готов к откликам'), ('reception_of_responses_closed', 'Прием откликов окончен'), ('project_completed', 'Проект завершен')], default='editing', max_length=100, verbose_name='Статус проекта'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='date_of_birth',
            field=models.DateField(help_text='Введите дату в формате "ГГГГ.ММ.ДД", пример: "2000 01 01".', validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1900, 1, 1)), django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 11, 1))], verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='telegram',
            field=models.CharField(max_length=32, validators=[projects.validators.validate_telegram]),
        ),
    ]
