# Generated by Django 4.2.6 on 2023-10-18 12:01

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, validators=[users.validators.NameUserValidator.validate_name], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, validators=[users.validators.NameUserValidator.validate_name], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.CharField(max_length=50, validators=[users.validators.NameUserValidator.validate_name], verbose_name='Отчество'),
        ),
    ]
