# Generated by Django 4.2.6 on 2023-11-03 20:25

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=256, unique=True, validators=[core.validators.EmailValidator.validate_email], verbose_name='Электронная почта'),
        ),
    ]
