# Generated by Django 4.2.6 on 2023-11-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('organizer', 'Организатор'), ('volunteer', 'Волонтер'), ('deleted', 'Удаленный')], default='admin', max_length=50, verbose_name='Роль'),
        ),
    ]
