# .github/workflows/main.yml
name: Main Volunteers-for-city-projects backend workflow

on:
  push:
    branches: [develop]

jobs:

  call_tests:
    name: Tests
    uses: volunteers-for-city-projects/volunteers-backend/.github/workflows/ci.yml@develop
    secrets: inherit

  call_build_backend:
    name: Build and Push backend in Docker Hub
    needs:
      - call_tests
    uses: volunteers-for-city-projects/volunteers-backend/.github/workflows/build_backend.yml@develop
    secrets: inherit

  call_build_gateway:
    name: Build and Push gateway in Docker Hub
    needs:
      - call_tests
    uses: volunteers-for-city-projects/volunteers-backend/.github/workflows/build_gateway.yml@develop
    secrets: inherit

  call_deploy:
    name: Deploy to production server
    needs:
      - call_build_backend
      - call_build_gateway
    uses: volunteers-for-city-projects/volunteers-backend/.github/workflows/deploy.yml@develop
    secrets: inherit

  # send_message:
  #   name: Send message in Telegram
  #   needs:
  #     - call_deploy
  #   uses: volunteers-for-city-projects/volunteers-backend/.github/workflows/send_message.yml@develop
  #   secrets: inherit
